ROWS = 15
COLS = 15
TILE_SIZE = 64
SIDE_PANEL = 330
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 24
TOTAL_WORLDS = 4
LEVEL_COMPLETE_REWARD = 100

# Animation
ANIMATION_DELAY = 15
FAST_FORWARD_SPEED = 4

# Enemy
MIN_SPAWN_COOLDOWN = 50
MAX_SPAWN_COOLDOWN = 500
