ROWS = 15
COLS = 15
TILE_SIZE = 64
SIDE_PANEL = 330
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 11
LEVEL_COMPLETE_REWARD = 100

# Animation
ANIMATION_DELAY = 30
FAST_FORWARD_SPEED = 4

# Enemy
SPAWN_COOLDOWN = 300
